In [1]:
# %pip install openai python-dotenv

In [2]:
import pandas as pd

meeting_note_csv_path = "../audio/싼기타_비싼기타_final.csv"
df_rttm = pd.read_csv(meeting_note_csv_path, sep='|')

display(df_rttm)

,start,end,speaker_id,duration,text,name
0,0.993,30.187,SPEAKER_01,29.194,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...,똑똑이
1,32.414,42.708,SPEAKER_00,10.294,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,송명근
2,41.662,44.024,SPEAKER_01,2.362,네 됐어요. 시작하시죠.\n,똑똑이
3,45.813,67.092,SPEAKER_00,21.279,좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\...,송명근
4,67.227,82.769,SPEAKER_01,15.542,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\...",똑똑이
5,84.659,102.547,SPEAKER_00,17.888,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...,송명근
6,103.492,117.515,SPEAKER_01,14.023,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...,똑똑이
7,119.742,138.676,SPEAKER_00,18.934,"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루...",송명근
8,139.351,168.967,SPEAKER_01,29.616,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...,똑똑이
9,170.924,192.304,SPEAKER_00,21.380,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타...,송명근
10,192.322,193.655,SPEAKER_01,1.333,NaN,똑똑이
11,192.777,193.503,SPEAKER_00,0.726,NaN,송명근
12,193.891,216.571,SPEAKER_01,22.680,아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니...,똑똑이
13,218.579,238.120,SPEAKER_00,19.541,하하 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타...,송명근
14,238.120,238.660,SPEAKER_01,0.540,NaN,똑똑이
15,238.188,239.352,SPEAKER_00,1.164,결국은 본인이 선택한...\n,송명근
16,239.858,240.651,SPEAKER_01,0.793,NaN,똑똑이
17,240.297,240.972,SPEAKER_00,0.675,NaN,송명근
18,241.040,251.317,SPEAKER_01,10.277,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...,똑똑이
19,253.696,271.533,SPEAKER_00,17.837,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...,송명근
20,272.140,304.557,SPEAKER_01,32.417,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타...,똑똑이
21,306.970,326.022,SPEAKER_00,19.052,"하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타...",송명근
22,326.360,335.455,SPEAKER_01,9.095,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...,똑똑이
23,337.548,355.908,SPEAKER_00,18.360,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...,송명근
24,356.245,363.991,SPEAKER_01,7.746,맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n,똑똑이
25,365.982,381.423,SPEAKER_00,15.441,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 ...",송명근
26,382.165,383.734,SPEAKER_01,1.569,어? 지금 도망가시는 건가요?\n,똑똑이
27,385.726,397.167,SPEAKER_00,11.441,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...,송명근
28,397.623,399.091,SPEAKER_01,1.468,NaN,똑똑이
29,401.437,406.583,SPEAKER_00,5.146,아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n,송명근
30,407.410,408.304,SPEAKER_01,0.894,화난 것 같은데?\n,똑똑이
31,410.093,417.451,SPEAKER_00,7.358,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으...",송명근
32,417.755,421.231,SPEAKER_01,3.476,화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n,똑똑이
33,423.644,429.348,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n,송명근

In [3]:
name_dict = {
    "SPEAKER_00": "AI",
    "SPEAKER_01": '송명근',
}

df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict[x])

display(df_rttm)

,start,end,speaker_id,duration,text,name
0,0.993,30.187,SPEAKER_01,29.194,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...,송명근
1,32.414,42.708,SPEAKER_00,10.294,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,AI
2,41.662,44.024,SPEAKER_01,2.362,네 됐어요. 시작하시죠.\n,송명근
3,45.813,67.092,SPEAKER_00,21.279,좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\...,AI
4,67.227,82.769,SPEAKER_01,15.542,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\...",송명근
5,84.659,102.547,SPEAKER_00,17.888,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...,AI
6,103.492,117.515,SPEAKER_01,14.023,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...,송명근
7,119.742,138.676,SPEAKER_00,18.934,"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루...",AI
8,139.351,168.967,SPEAKER_01,29.616,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...,송명근
9,170.924,192.304,SPEAKER_00,21.380,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타...,AI
10,192.322,193.655,SPEAKER_01,1.333,NaN,송명근
11,192.777,193.503,SPEAKER_00,0.726,NaN,AI
12,193.891,216.571,SPEAKER_01,22.680,아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니...,송명근
13,218.579,238.120,SPEAKER_00,19.541,하하 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타...,AI
14,238.120,238.660,SPEAKER_01,0.540,NaN,송명근
15,238.188,239.352,SPEAKER_00,1.164,결국은 본인이 선택한...\n,AI
16,239.858,240.651,SPEAKER_01,0.793,NaN,송명근
17,240.297,240.972,SPEAKER_00,0.675,NaN,AI
18,241.040,251.317,SPEAKER_01,10.277,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...,송명근
19,253.696,271.533,SPEAKER_00,17.837,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...,AI
20,272.140,304.557,SPEAKER_01,32.417,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타...,송명근
21,306.970,326.022,SPEAKER_00,19.052,"하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타...",AI
22,326.360,335.455,SPEAKER_01,9.095,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...,송명근
23,337.548,355.908,SPEAKER_00,18.360,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...,AI
24,356.245,363.991,SPEAKER_01,7.746,맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n,송명근
25,365.982,381.423,SPEAKER_00,15.441,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 ...",AI
26,382.165,383.734,SPEAKER_01,1.569,어? 지금 도망가시는 건가요?\n,송명근
27,385.726,397.167,SPEAKER_00,11.441,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...,AI
28,397.623,399.091,SPEAKER_01,1.468,NaN,송명근
29,401.437,406.583,SPEAKER_00,5.146,아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n,AI
30,407.410,408.304,SPEAKER_01,0.894,화난 것 같은데?\n,송명근
31,410.093,417.451,SPEAKER_00,7.358,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으...",AI
32,417.755,421.231,SPEAKER_01,3.476,화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n,송명근
33,423.644,429.348,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n,AI

In [4]:
meeting_note_txt = df_rttm[['start', 'end', 'name', 'text']].to_json(orient='records',
force_ascii=False)
print(meeting_note_txt)

[{"start":0.993,"end":30.187,"name":"송명근","text":"지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 되요 자연스럽게\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n두 중에 어떤 역할 맡으실래요?\n"},{"start":32.414,"end":42.708,"name":"AI","text":"좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?\n네 맞아요. 준비 되셨나요?\n"},{"start":41.662,"end":44.024,"name":"송명근","text":"네 됐어요. 시작하시죠.\n"},{"start":45.813,"end":67.092,"name":"AI","text":"좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\n실수도 많고 기타에 익숙해지는\n과정이 필요하니까 비싼 기타보다는 부담없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n"},{"start":67.227,"end":82.769,"name":"송명근","text":"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타로 사고 싼 기타로 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n"},{"start":84.659,"end":102.547,"name":"AI","text":"그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 더 크지 않을까요?\n초보 때는 실습을 많이 하니까\n쌍기타로 마음 편히 연습할 수 있는게\n더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 그 비싼 기타를 살 건데\n"},{"start":103.492,"end":117.515,"name":"송명근","text":"싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\n기타를 싼 거 산다고 달라지나요?\n"},{"start":119.742,"end":138.676,"name":"AI","text":"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에\n부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요\n그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.\n그리고 쌍기타도 요즘은\n품질이 꽤 좋아서 연습용으로\n"},{"start":139.351,"end":168.967,"name":"송명근","text":"충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안될 때 안될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요\n"},{"start":170.924,"end":192.304,"name":"AI","text":"하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n쌍기타로 시작해서\n부담없이 연습하고\n정말 기타에 흥미가 생기면 그때 비슷하게 부담 없이 연습하고\n정말 기타에 흥미가 생기면\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠\n"},{"start":192.322,"end":193.655,"name":"송명근","text":null},{"start":192.777,"end":193.503,"name":"AI","text":null},{"start":193.891,"end":216.571,"name":"송명근","text":"아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n"},{"start":218.579,"end":238.12,"name":"AI","text":"하하 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요. 그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n"},{"start":238.12,"end":238.66,"name":"송명근","text":null},{"start":238.188,"end":239.352,"name":"AI","text":"결국은 본인이 선택한...\n"},{"start":239.858,"end":240.651,"name":"송명근","text":null},{"start":240.297,"end":240.972,"name":"AI","text":null},{"start":241.04,"end":251.317,"name":"송명근","text":"근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n"},{"start":253.696,"end":271.533,"name":"AI","text":"맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게\n선택하는 게 최선이겠네요.\n"},{"start":272.14,"end":304.557,"name":"송명근","text":"아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로\n비싼 기타를 치던 사람이\n싼 기타를 치면은 아 이게\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작을 하는 게 좋죠.\n"},{"start":306.97,"end":326.022,"name":"AI","text":"하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?\n"},{"start":326.36,"end":335.455,"name":"송명근","text":"맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n"},{"start":337.548,"end":355.908,"name":"AI","text":"그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n"},{"start":356.245,"end":363.991,"name":"송명근","text":"맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n"},{"start":365.982,"end":381.423,"name":"AI","text":"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 이야기 나누는 게 더 중요한 것 같아요.\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n"},{"start":382.165,"end":383.734,"name":"송명근","text":"어? 지금 도망가시는 건가요?\n"},{"start":385.726,"end":397.167,"name":"AI","text":"아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 지금 혹시 화나셨나요?\n"},{"start":397.623,"end":399.091,"name":"송명근","text":null},{"start":401.437,"end":406.583,"name":"AI","text":"아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n"},{"start":407.41,"end":408.304,"name":"송명근","text":"화난 것 같은데?\n"},{"start":410.093,"end":417.451,"name":"AI","text":"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으시면 편하게 말씀해 주세요. 아니요.\n"},{"start":417.755,"end":421.231,"name":"송명근","text":"화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n"},{"start":423.644,"end":429.348,"name":"AI","text":"알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n"}]

In [5]:
system_prompt = f'''
너는 회의 내용을 요약하는 봇이다. 아래 회의록을 읽고, 주요 내용을 요약하라.
결과는 마크다운 형식으로 작성한다.

아래 형식에 맞추어 작성하라.

# 회의 제목
## 주요 내용
## 참석자별 입장
## 결정 사항
============== 이하 회의록 ==============

{ meeting_note_txt}
'''

In [6]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()

api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI(api_key=api_key)

In [7]:
response = client.chat.completions.create(
    model = 'gpt-4o',
    temperature=0.1,
    messages=[
        {"role": "system", "content": system_prompt},
    ]
)

# 요약 결과를 파일로 저장
summary = response.choices[0].message.content
summary = summary.strip() # 좌우 공백 제거

print(summary)

# 기타 구매 토론 회의
## 주요 내용
이번 회의에서는 기타를 처음 시작할 때 싼 기타로 시작하는 것이 좋은지, 비싼 기타로 시작하는 것이 좋은지에 대한 토론이 진행되었습니다. 싼 기타로 시작하면 부담 없이 연습할 수 있고, 비싼 기타로 시작하면 이중 지출을 막을 수 있다는 주장이 오갔습니다. 또한, 비싼 기타는 연습에 대한 동기부여가 될 수 있지만, 초보자에게는 부담이 될 수 있다는 의견도 나왔습니다.

## 참석자별 입장
- **송명근**: 비싼 기타로 시작하는 것이 좋다고 주장. 이중 지출을 막을 수 있고, 비싼 기타가 연습에 대한 동기부여가 될 수 있다고 강조.
- **AI**: 싼 기타로 시작하는 것이 좋다고 주장. 초보자에게 부담이 적고, 기타에 대한 흥미를 잃지 않도록 도와준다고 설명.

## 결정 사항
결정된 사항은 없으며, 각자의 스타일과 상황에 맞게 기타를 선택하는 것이 중요하다는 결론에 도달했습니다. 중요한 것은 기타에 대한 열정과 꾸준한 연습이라는 점에 참석자들이 동의했습니다.

In [9]:
with open('../audio/guitar_summary.md', 'w', encoding='utf-8') as f:
    f.write(summary)

In [13]:
df_meeting_note = df_rttm[['start', 'end', 'name', 'text']].copy()
df_meeting_note.dropna(inplace=True)

meeting_note_dict = df_meeting_note.to_dict(orient='records') # 딕셔너리 형태로 변환
meeting_note_dict

[{'start': 0.993,
  'end': 30.187,
  'name': '송명근',
  'text': '지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 되요 자연스럽게\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n두 중에 어떤 역할 맡으실래요?\n'},
 {'start': 32.414,
  'end': 42.708,
  'name': 'AI',
  'text': '좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?\n네 맞아요. 준비 되셨나요?\n'},
 {'start': 41.662, 'end': 44.024, 'name': '송명근', 'text': '네 됐어요. 시작하시죠.\n'},
 {'start': 45.813,
  'end': 67.092,
  'name': 'AI',
  'text': '좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\n실수도 많고 기타에 익숙해지는\n과정이 필요하니까 비싼 기타보다는 부담없이 연습할 수 있는 싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n'},
 {'start': 67.227,
  'end': 82.769,
  'name': '송명근',
  'text': '아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타로 사고 싼 기타로 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n'},
 {'start': 84.659,
  'end': 102.547,
  'name': 'AI',
  'text': '그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 더 크지 않을까요?\n초보 때는 실습을 많이 하니까\n쌍기타로 마음 편히 연습할 수 있는게\n더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는 게 더 의미 있지 않을까요? 아니 근데 어차피 그 비싼 기타를 살 건데\n'},
 {'start': 103.492,
  'end': 117.515,
  'name': '송명근',
  'text': '싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\n기타를 싼 거 산다고 달라지나요?\n'},
 {'start': 119.742,
  'end': 138.67600000000002,
  'name': 'AI',
  'text': '하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에\n부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요\n그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.\n그리고 쌍기타도 요즘은\n품질이 꽤 좋아서 연습용으로\n'},
 {'start': 139.351,
  'end': 168.967,
  'name': '송명근',
  'text': '충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안될 때 안될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요\n'},
 {'start': 170.924,
  'end': 192.304,
  'name': 'AI',
  'text': '하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n쌍기타로 시작해서\n부담없이 연습하고\n정말 기타에 흥미가 생기면 그때 비슷하게 부담 없이 연습하고\n정말 기타에 흥미가 생기면\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠\n'},
 {'start': 193.891,
  'end': 216.571,
  'name': '송명근',
  'text': '아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n측면에서도 비싼 기타가 훨씬 도움이 된다고\n생각을 합니다.\n'},
 {'start': 218.579,
  'end': 238.12,
  'name': 'AI',
  'text': '하하 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요. 그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n'},
 {'start': 238.188, 'end': 239.352, 'name': 'AI', 'text': '결국은 본인이 선택한...\n'},
 {'start': 241.04,
  'end': 251.317,
  'name': '송명근',
  'text': '근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n'},
 {'start': 253.696,
  'end': 271.533,
  'name': 'AI',
  'text': '맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게\n선택하는 게 최선이겠네요.\n'},
 {'start': 272.14,
  'end': 304.557,
  'name': '송명근',
  'text': '아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로\n비싼 기타를 치던 사람이\n싼 기타를 치면은 아 이게\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작을 하는 게 좋죠.\n'},
 {'start': 306.97,
  'end': 326.022,
  'name': 'AI',
  'text': '하하, 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요.\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?\n'},
 {'start': 326.36,
  'end': 335.455,
  'name': '송명근',
  'text': '맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n'},
 {'start': 337.548,
  'end': 355.908,
  'name': 'AI',
  'text': '그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n'},
 {'start': 356.245,
  'end': 363.991,
  'name': '송명근',
  'text': '맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n'},
 {'start': 365.982,
  'end': 381.423,
  'name': 'AI',
  'text': '아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는 재밌게 이야기 나누는 게 더 중요한 것 같아요.\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n'},
 {'start': 382.165,
  'end': 383.734,
  'name': '송명근',
  'text': '어? 지금 도망가시는 건가요?\n'},
 {'start': 385.726,
  'end': 397.167,
  'name': 'AI',
  'text': '아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 지금 혹시 화나셨나요?\n'},
 {'start': 401.437,
  'end': 406.583,
  'name': 'AI',
  'text': '아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n'},
 {'start': 407.41, 'end': 408.304, 'name': '송명근', 'text': '화난 것 같은데?\n'},
 {'start': 410.093,
  'end': 417.451,
  'name': 'AI',
  'text': '네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으시면 편하게 말씀해 주세요. 아니요.\n'},
 {'start': 417.755,
  'end': 421.231,
  'name': '송명근',
  'text': '화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n'},
 {'start': 423.644,
  'end': 429.348,
  'name': 'AI',
  'text': '알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n'}]

In [16]:
for row in meeting_note_dict:
    if not isinstance(row['text'], str): # 텍스트가 아닌 다른 형식인 경우 통과
        continue
    correction_system_prompt = f'''
        너는 주어진 회의 녹취록을 수정 및 보완하는 봇이다.
        주어진 회의 녹취록은 STT로 작성된 결과이므로, 이 중에 오류가 있는 부분을 찾아내고 수정하라.
        
        표현, 말투는 최대한 원본과 일치하도록 유지하되, 잘못 받아적은 내용을 수정하라.
        원본의 내용을 최대한 살리되, 잘못된 내용만 수정하라.
        어떤 경우에는 A라는 사람이 말한 내용을 B가 말한 것으로 잘못 기록된 경우도 있을 수 있다.
        이런 경우에는 문맥을 고려하여 수정하라.
        
        원본 내용 중 빠지거나, 추가되거나, 잘못 기록된 부분을 찾아내어 수정하라. 수정된 메시지
        이외에는 아무것도 작성하지 말라.
        --------------------------
        회의 요약문 : {summary}
        
        --------------------------
        회의 녹취록 전문 : {df_meeting_note.to_json(orient='records', force_ascii=False)}
        --------------------------
        확인할 메시지 원본: {row['text']}
        '''

    response = client.chat.completions.create(
        model='gpt-4o',
        temperature=0.1,
        messages=[
            {"role": "system", "content": correction_system_prompt},
        ]
    )

    correction = response.choices[0].message.content
    if ':' in correction: # "수정: " 과 같은 형식으로 반환되는 경우 해결
        correction = correction.split(':')[-1]

        correction = correction.strip()  # 좌우 공백 제거
        
        print(row['name'])
        print(row['text'])
        print(correction)
        print('--------------------------')

        row['corrected_text'] = correction

In [18]:
import json

with open('../audio/guitar_meeting_note_corrected.json', 'w', encoding='utf-8') as f:
    json.dump(meeting_note_dict, f, ensure_ascii=False, indent=4)

In [25]:
md_template = ""

for row in meeting_note_dict:
    md_template += f"- **{row['name']}** : {row['text']}\n"

with open('../audio/guitar_meeting_note_corrected.md', 'w', encoding='utf-8') as f:
    f.write(md_template)

In [26]:
%pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting lxml>=3.1.0 (from python-docx)
  Downloading lxml-6.1.0-cp311-cp311-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\Users\a\LLM\ch05dia\Lib\site-packages (from python-docx) (4.15.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Downloading lxml-6.1.0-cp311-cp311-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 4.0/4.0 MB 26.9 MB/s  0:00:00
Installing collected packages: lxml, python-docx

   ---------------------------------------- 0/2 [lxml]
   ---------------------------------------- 0/2 [lxml]
   ---------------------------------------- 0/2 [lxml]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   ---------------------------------------- 2/2 [python-docx]

Successfully installed lxml-6.1.0 python-docx-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [28]:
from docx import Document

document = Document()   # (1)  docx 객체 생성
document.add_heading('회의록', level=1) # (2) 제목 추가

table = document.add_table(rows=1, cols=2) # (3) 테이블 생성
table.style = 'Table Grid' # (4) 테이블 스타일 지정

hdr_cells = table.rows[0].cells # (5) 첫 번째 행에 셀 추가
hdr_cells[0].text = 'Speaker' # (6) 첫 번째 셀에 Speaker 추가
hdr_cells[1].text = 'Content'   # (7) 두 번째 셀에 Content 추가

# (8) 수정된 녹취록 파일을 읽어들여서 테이블에 추가
for row in meeting_note_dict:
    row_cells = table.add_row().cells
    row_cells[0].text = row['name']
    row_cells[1].text = row['text']


document.save('../audio/guitar_meeting_note_corrected.docx')